version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: ridesmart-mysql
    environment:
      MYSQL_DATABASE: smart_bike_rental
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ridesmart-app:
    build: .
    container_name: ridesmart-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/smart_bike_rental?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb

volumes:
  mysql_data:
